version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: clinicdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - clinic-net

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: clinicdb
      JWT_SECRET: supersecreto
      JWT_EXPIRES_IN: 1h
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - clinic-net

volumes:
  db_data:

networks:
  clinic-net:
